### ISSUE TITLE
大佬 有使用教程文档吗

### ISSUE THREAD

**Issue by phosic** [Akimio521/MediaWarp#2]
大佬。怎么使用呢，求部署文档，谢谢

**Comment by blacktea1891** [comment]
同需要一个部署文档，使用说明

**Comment by rkongzy** [comment]
同求一个。映射了config文件夹，添加配置文件后，容器日志一直显示启动中

**Comment by Akimio521** [comment]
1. 目前程序还未定型，配置文件变化幅度较大，暂时不会提供教程
2. 关于配置文件可以在此issue讨论
3. 大多参数example中已叙述很清楚
4. 现实启动中后可以访问对应端口

**Comment by phosic** [comment]
> 同求一个。映射了config文件夹，添加配置文件后，容器日志一直显示启动中
你的服务启动起来了吗

**Comment by rkongzy** [comment]
> > 同求一个。映射了config文件夹，添加配置文件后，容器日志一直显示启动中
> > 你的服务启动起来了吗

没启动起来
services:
    mediawarp:
        container_name: mediawarp
        restart: always
        network_mode: host
        volumes:
            - /vol1/1000/docker/MediaWarp/config:/config
        image: akimio/mediawarp
用上述compose部署后，显示启动中，但是访问9000端口网页无法打开

**Comment by Akimio521** [comment]
截止至2024.9.6，docker镜像latest版本为0.0.2，对比目前main分支中config文件有变化，需要查看对应的config.yaml.example进行配置

**Comment by rkongzy** [comment]
> 截止至2024.9.6，docker镜像latest版本为0.0.2，对比目前main分支中config文件有变化，需要查看对应的config.yaml.example进行配置

感谢回复提醒，用release0.0.2的config可以访问web

**Comment by phosic** [comment]
> > 截止至2024.9.6，docker镜像latest版本为0.0.2，对比目前main分支中config文件有变化，需要查看对应的config.yaml.example进行配置
> 
> 感谢回复提醒，用release0.0.2的config可以访问web

大佬，你的服务起来了，strm 可以302了吗 ？EmbyServer中Strm文件的前缀  这个配置需要怎么填写

**Comment by rkongzy** [comment]
> > > 截止至2024.9.6，docker镜像latest版本为0.0.2，对比目前main分支中config文件有变化，需要查看对应的config.yaml.example进行配置
> > 
> > 
> > 感谢回复提醒，用release0.0.2的config可以访问web
> 
> 大佬，你的服务起来了，strm 可以302了吗 ？EmbyServer中Strm文件的前缀 这个配置需要怎么填写
我准备等程序定型后再折腾了，你用上面的compose和0.0.2版本zip压缩包里的config.yaml.example自己试下吧，config.yaml.example修改下然后重命名为config.yaml，上传到映射出来的config文件夹里就好

**Comment by phosic** [comment]
> > > > 截止至2024.9.6，docker镜像latest版本为0.0.2，对比目前main分支中config文件有变化，需要查看对应的config.yaml.example进行配置
> > > 
> > > 
> > > 感谢回复提醒，用release0.0.2的config可以访问web
> > 
> > 
> > 大佬，你的服务起来了，strm 可以302了吗 ？EmbyServer中Strm文件的前缀 这个配置需要怎么填写
> > 我准备等程序定型后再折腾了，你用上面的compose和0.0.2版本zip压缩包里的config.yaml.example自己试下吧，config.yaml.example修改下然后重命名为config.yaml，上传到映射出来的config文件夹里就好

感谢。终于搞定了，播放成功了

**Comment by yating1022** [comment]
> > > > 截止至2024.9.6，docker镜像latest版本为0.0.2，对比目前main分支中config文件有变化，需要查看对应的config.yaml.example进行配置
> > > 
> > > 
> > > 感谢回复提醒，用release0.0.2的config可以访问web
> > 
> > 
> > 大佬，你的服务起来了，strm 可以302了吗 ？EmbyServer中Strm文件的前缀 这个配置需要怎么填写
> > 我准备等程序定型后再折腾了，你用上面的compose和0.0.2版本zip压缩包里的config.yaml.example自己试下吧，config.yaml.example修改下然后重命名为config.yaml，上传到映射出来的config文件夹里就好

我弄完了，但是只有web端去调用pot播放器成功了，其他比如windows客户端和yamby都无法正常重定向

**Comment by Rayd62** [comment]
Hi 大佬，使用的v0.0.5 的容器部署。
strm 用autofilm 生成模式为的"AlistPath" ，生成的链接前面加上我alist 服务器地址能打开对应的视频。
mediawarp 配置如下：
```yaml
Port: 9000                                  # MideWarp监听端口

MediaServer:                                # 媒体服务器相关设置
  Type: Emby                                # 媒体服务器类型（可选选项：Emby）
  ADDR: http://127.0.0.1:8096               # 媒体服务器地址
  AUTH: *****    # 使用的Emby API

Cache:                                      # 缓存设置
  Type: Memory                              # 缓存类型（可选项：Memory内存缓存）
  WebCache: False                           # 是否启用Web缓存中间件（若MdiaWarp离上游服务距离较近则不建议启用）

Logger:                                     # 日志设定
  AccessLogger:                             # 访问日志设定
    Console: True                           # 是否将访问日志文件输出到终端中
    File: False                             # 是否将访问日志文件记录到文件中
  ServiceLogger:                            # 服务日志设定
    Console: True                           # 是否将服务日志文件输出到终端中
    File: True                              # 是否将服务日志文件记录到文件中

Web:                                        # Web页面修改相关设置
  Enable: False                              # 总开关
  Custom: False                              # 是否加载自定义静态资源
  Index: True                               # 是否从static目录读取index.html文件
  Head: |                                   # 是否添加自定义字段到index.html的HEAD中
    <script src="/MediaWarp/static/custom/emby-front-end-mod/actor-plus.js"></script>
    <script src="/MediaWarp/static/custom/emby-front-end-mod/emby-swiper.js"></script>
    <script src="/MediaWarp/static/custom/emby-front-end-mod/emby-tab.js"></script>
    <script src="/MediaWarp/static/custom/emby-front-end-mod/fanart-show.js"></script>
    <script src="/MediaWarp/static/custom/emby-front-end-mod/playbackRate.js"></script>

  ExternalPlayerUrl: True                   # 是否开启外置播放器
  ActorPlus: True                           # 过滤没有头像的演员和制作人员
  FanartShow: False                         # 显示同人图（fanart图）
  Danmaku: True                             # Web显示弹幕
  BeautifyCSS: True                         # Emby美化CSS样式

ClientFilter:                               # 客户端过滤器
  Enable: False                             # 是否启用客户端过滤器
  Mode: BlackList # WhileList / BlackList   # 黑白名单模式
  ClientList:                               # 名单列表
    - Fileball


# 302重定向相关配置

HTTPStrm:
  Enable: True                              # 是否开启HttpStrm重定向
  PrefixList:                               # EmbyServer中Strm文件的前缀（符合该前缀的Strm文件且被正确识别为http协议都会路由到该规则下）
    - /media/strm/http
    - /media/strm/https

AlistStrm:                                  # AlistStrm相关配置（Strm文件内容是Alist上文件的路径，目前仅支持适配Alist V3）
  Enable: True                              # 是否启用AlistStrm重定向
  List:                                     # Alist服务关配置列表
    - ADDR: https://alist.hf2.life:8686       # 这里是否可以使用http://127.0.0.1:5244 ？我使用的nginx 做了一个反代在alist 前面，开了ssl
      Username: ****                       # Alist服务器账号
      Password: ****                  # Alist服务器密码
      PrefixList:                           # EmbyServer中Strm文件的前缀（符合该前缀的Strm文件都会路由到该规则下）
        - /media               # 同一个Alist可以有多个前缀规则
```

使用infuse 客户端能看到资源，无法正常播放。docker compose logs 显示如下
```bash
【AccessLog】 2024-11-18 02:48:51 | 200 | 4.906209ms | GET    |14.155.201.121 "/Users/b24f5ebde6524d6a97f89a77347fb5cc/Items/369249?fields=DateCreated%2CEtag%2CGenres%2CMediaSources%2CAlternateMediaSources%2COverview%2CParentId%2CPath%2CPeople%2CProviderIds%2CSortName%2CRecursiveItemCount%2CChildCount%2CCommunityRating%2COfficialRating%2CPremiereDate"
mediawarp  | 【WARNING】 2024-11-18 02:48:51 | 请求 ItemsServiceQueryItem 失败：invalid character 'A' looking for beginning of value
mediawarp  | 【AccessLog】 2024-11-18 02:48:51 | 404 | 12.469677ms | GET    |14.155.201.121 "/Videos/369249/stream?mediasourceid=26e379f242f2af8e3d566e93e2f184b5&static=true
```

logs 目录下的service.log 如下
```bash
【WARNING】 2024-11-18 01:28:58 | 读取文件内容出错，错误信息：stat /static/index.html: no such file or directory
【WARNING】 2024-11-18 01:30:02 | 读取文件内容出错，错误信息：stat /static/index.html: no such file or directory
【WARNING】 2024-11-18 01:55:42 | 请求 FsGet 失败：failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed to list objs: Get "https://webapi.115.com/files?aid=1&asc=1&cid=0&fc_mix=0&format=json&limit=9999&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0": read tcp **********:50642->***********00:443: read: connection reset by peer
【WARNING】 2024-11-18 01:55:44 | 请求 FsGet 失败：failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed to list objs: Get "https://webapi.115.com/files?aid=1&asc=1&cid=0&fc_mix=0&format=json&limit=9999&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0": read tcp **********:50652->***********00:443: read: connection reset by peer
【WARNING】 2024-11-18 02:10:24 | 请求 FsGet 失败：failed link: failed get link: Post "https://proapi.115.com/app/chrome/downurl?t=1731895823": read tcp **********:55144->***********00:443: read: connection reset by peer
【WARNING】 2024-11-18 02:13:19 | 请求 FsGet 失败：token is invalidated
【WARNING】 2024-11-18 02:15:05 | 请求 ItemsServiceQueryItem 失败：invalid character 'A' looking for beginning of value
【WARNING】 2024-11-18 02:15:14 | 请求 ItemsServiceQueryItem 失败：invalid character 'A' looking for beginning of value
【WARNING】 2024-11-18 02:41:12 | 请求 ItemsServiceQueryItem 失败：invalid character 'A' looking for beginning of value
【WARNING】 2024-11-18 02:48:51 | 请求 ItemsServiceQueryItem 失败：invalid character 'A' looking for beginning of value
```

大佬能教一教怎么搞定这个吗
