### ISSUE TITLE
[错误报告]: Afusekt 播放器使用 HTTPStrm 直链无法正常 302

### ISSUE THREAD

**Issue by DDSDerek** [Akimio521/MediaWarp#37]
### 确认

- [x] 我的版本是最新版本，我的版本号与 [version](https://github.com/Akimio521/MediaWarp/releases/latest) 相同。
- [x] 我已经 [issue](https://github.com/Akimio521/MediaWarp/issues) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

0.1.1-PreRelease-79112fe

### 当前程序版本的详细信息

{   "AppVersion": "0.1.1-PreRelease-79112fe",   "CommitHash": "79112fed4c0c286042f1027c39a6a3e6b99d6bda",   "BuildData": "2025-05-31 11:45:33 +08:00",   "GoVersion": "go1.24.1",   "OS": "linux",   "Arch": "amd64" }

### 运行环境

Linux

### 媒体服务器类型

Emby

### 媒体服务器版本

4.8.10.0

### 客户端版本

Afusekt/2.6.2

### 问题类型

Strm 文件播放问题

### 问题描述

Afusekt播放HTTPStrm直链时无法正常302跳转，返回的是官方播放连接

同样配置环境在Web端和FileBall播放正常

### 发生问题时相关日志

```bash
DEBUG】       2025-06-01 09:30:24 | /data2/strm_test/影视/电视剧/欧美剧/鹦鹉螺号 (2024)/Season 1/鹦鹉螺号 - S01E01 - 第 1 集.strm 成功匹配路径：/data2/strm_test，Strm 类型：HTTPStrm
【INFO】        2025-06-01 09:30:24 | 鹦鹉螺号 - S01E01 - 第 1 集 强制禁止转码，直链播放链接为：/videos/58001/stream?MediaSourceId=5f10769b4352f606a16f0d6ae958d9b8&Static=true&api_key=546e450594a1423fa4ec7ae42afac88a
```

### 发生问题时配置文件

```yaml
Port: '9096'                                # MideWarp 监听端口

MediaServer:                                # 媒体服务器相关设置
  Type: Emby                                # 媒体服务器类型（可选选项：Emby、Jellyfin）
  ADDR: http://192.168.31.96:8096           # 媒体服务器地址
  AUTH: f0ef0d45b5124085xxxxxxxxxxxxxxx1    # 媒体服务器认证方式

Logger:                                     # 日志设定
  AccessLogger:                             # 访问日志设定
    Console: False                          # 是否将访问日志文件输出到终端中
    File: True                              # 是否将访问日志文件记录到文件中
  ServiceLogger:                            # 服务日志设定
    Console: True                           # 是否将服务日志文件输出到终端中
    File: True                              # 是否将服务日志文件记录到文件中

Web:                                        # Web 页面修改相关设置
  Enable: True                              # 总开关
  Custom: True                              # 是否加载自定义静态资源
  Index: False                              # 是否从 custom 目录读取 index.html 文件 
  Head: |                                   # 是否添加自定义字段到 index.html 的头部中
    <script src="/MediaWarp/custom/emby-front-end-mod/actor-plus.js"></script>
    <script src="/MediaWarp/custom/emby-front-end-mod/emby-swiper.js"></script>
    <script src="/MediaWarp/custom/emby-front-end-mod/emby-tab.js"></script>
    <script src="/MediaWarp/custom/emby-front-end-mod/fanart-show.js"></script>
    <script src="/MediaWarp/custom/emby-front-end-mod/playbackRate.js"></script>

  Crx: True                                 # crx 美化（Emby：https://github.com/Nolovenodie/emby-crx；Jellyfin：https://github.com/newday-life/jellyfin-crx）
  ActorPlus: True                           # 过滤没有头像的演员和制作人员
  FanartShow: True                          # 显示同人图（fanart 图）
  ExternalPlayerUrl: True                   # 是否开启外置播放器
  Danmaku: True                             # Web 弹幕（Emby：https://github.com/9channel/dd-danmaku；Jellyfin：https://github.com/Izumiko/jellyfin-danmaku）
  VideoTogether: True                       # 共同观影，详情见 https://videotogether.github.io/

ClientFilter:                               # 客户端过滤器
  Enable: False                             # 是否启用客户端过滤器
  Mode: BlackList # WhileList / BlackList   # 黑白名单模式
  ClientList:                               # 名单列表
    - Fileball
    - Infuse

HTTPStrm:                                   # HTTPStrm 相关配置（Strm 文件内容是 标准 HTTP URL）
  Enable: True                              # 是否开启 HttpStrm 重定向
  TransCode: False                          # False：强制关闭转码 True：保持原有转码设置
  FinalURL: True
  PrefixList:                               # EmbyServer 中 Strm 文件的前缀（符合该前缀的 Strm 文件且被正确识别为 HTTP 协议都会路由到该规则下）
    - /data2/strm_test
AlistStrm:                                  # AlistStrm 相关配置（Strm 文件内容是 Alist 上文件的路径，目前仅支持适配 Alist V3）
  Enable: True                              # 是否启用 AlistStrm 重定向
  TransCode: True                           # False：强制关闭转码 True：保持原有转码设置
  RawURL: False                             # Fasle：响应 Alist 服务器的直链（要求客户端可以访问到 Alist） True：直接响应 Alist 上游的真实链接（alist api 中的 raw_url 属性）
  List:                                     # Alist 服务关配置列表
    - ADDR: http://192.168.1.100:5244       # Alist 服务器地址
      Username: admin                       # Alist 服务器账号
      Password: adminadmin                  # Alist 服务器密码
      PrefixList:                           # EmbyServer 中 Strm 文件的前缀（符合该前缀的 Strm 文件都会路由到该规则下）
        - /media/strm/MyAlist               # 同一个 Alist 可以有多个前缀规则
        - /mnt/cd2/strm
    - ADDR: https://xiaoya.com              # 可以填写多个配置
      Token: xxxxxxx                        # Token 优先级高于 Username 和 Password
      PrefixList:
        - /media/strm

Subtitle:                                   # 字体相关设置（仅 Emby 支持）
  Enable: True                              # 启用
  SRT2ASS: True                             # SRT 字幕转 ASS 字幕
  ASSStyle:                                 # SRT 字幕转 ASS 字幕使用的样式
    - "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour,
      BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle,
      BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
    - "Style: Default,楷体,20,&H03FFFFFF,&H00FFFFFF,&H00000000,&H02000000,-1,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1"
```
