### ISSUE TITLE
[错误报告]: 内网使用HTTP无法访问MediaWarp的监听端口

### ISSUE THREAD

**Issue by Star-ZER0** [Akimio521/MediaWarp#40]
### 确认

- [x] 我的版本是最新版本，我的版本号与 [version](https://github.com/Akimio521/MediaWarp/releases/latest) 相同。
- [x] 我已经 [issue](https://github.com/Akimio521/MediaWarp/issues) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

0.1.1

### 当前程序版本的详细信息

{"AppVersion":"0.1.1","CommitHash":"e8e0a76712f573522166eadcfccf682a81a3ecd4","BuildData":"2025-06-02 10:36:57 +08:00","GoVersion":"go1.24.1","OS":"linux","Arch":"amd64"}

### 运行环境

Docker

### 媒体服务器类型

Jellyfin

### 媒体服务器版本

nyanmisaka/jellyfin:latest    a3deaaefacaf

### 客户端版本

浏览器 Microsoft Edge & Mozilla Firefox

### 问题类型

其他问题

### 问题描述

使用内网地址http://192.168.1.1:8096访问MediaWarp的监听端口（监听端口在容器内部为9000映射为8096，外部端口改为9000仍能复现问题），以下为浏览器控制台信息

![Image](https://github.com/user-attachments/assets/cb585421-8670-476f-95b6-b05dd361c02a)

### 发生问题时相关日志

```bash
███╗   ███╗███████╗██████╗ ██╗ █████╗ ██╗    ██╗ █████╗ ██████╗ ██████╗ 

████╗ ████║██╔════╝██╔══██╗██║██╔══██╗██║    ██║██╔══██╗██╔══██╗██╔══██╗

██╔████╔██║█████╗  ██║  ██║██║███████║██║ █╗ ██║███████║██████╔╝██████╔╝

██║╚██╔╝██║██╔══╝  ██║  ██║██║██╔══██║██║███╗██║██╔══██║██╔══██╗██╔═══╝ 

██║ ╚═╝ ██║███████╗██████╔╝██║██║  ██║╚███╔███╔╝██║  ██║██║  ██║██║     

╚═╝     ╚═╝╚══════╝╚═════╝ ╚═╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ 

=========================== MediaWarp 0.1.1 ===========================

【INFO】        2025-06-07 19:06:42 | 上游媒体服务器类型：Jellyfin，服务器地址：http://jellyfin:8096

【INFO】        2025-06-07 19:06:42 | MediaWarp 监听端口：9000

【INFO】        2025-06-07 19:06:42 | 客户端过滤中间件未启用

【INFO】        2025-06-07 19:06:42 | MediaWarp 启动成功

【Access】 2025-06-07 19:06:44 | 302 | 1.886028ms | GET     | 192.168.1.2 "/"

2025/06/07 19:06:44 http: proxy error: context canceled

【Access】 2025-06-07 19:06:44 | 502 | 356.649µs  | GET     | 192.168.1.2 "/web/"

【Access】 2025-06-07 19:07:19 | 302 | 1.771604ms | GET     | 192.168.1.2 "/"

【Access】 2025-06-07 19:07:19 | 200 | 2.569527ms | GET     | 192.168.1.2 "/web/"

【Access】 2025-06-07 19:07:19 | 404 | 990.27µs   | GET     | 192.168.1.2 "/favicon.ico"
```

### 发生问题时配置文件

```yaml
Port: 9000                                  # MideWarp 监听端口

MediaServer:                                # 媒体服务器相关设置
  Type: Jellyfin                            # 媒体服务器类型（可选选项：Emby、Jellyfin）
  ADDR: http://jellyfin:8096                # 媒体服务器地址
  AUTH: faxxxxxxxxxxxxxxxxxxxxxxxxxxxx0f    # 媒体服务器认证方式

Logger:                                     # 日志设定
  AccessLogger:                             # 访问日志设定
    Console: True                           # 是否将访问日志文件输出到终端中
    File: False                             # 是否将访问日志文件记录到文件中
  ServiceLogger:                            # 服务日志设定
    Console: True                           # 是否将服务日志文件输出到终端中
    File: True                              # 是否将服务日志文件记录到文件中

Web:                                        # Web 页面修改相关设置
  Enable: True                              # 总开关
  Custom: False                             # 是否加载自定义静态资源
  Index: False                              # 是否从 custom 目录读取 index.html 文件 
  Head: |                                   # 是否添加自定义字段到 index.html 的头部中

  Crx: True                                 # crx 美化（Emby：https://github.com/Nolovenodie/emby-crx；Jellyfin：https://github.com/newday-life/jellyfin-crx）
  ActorPlus: False                          # 过滤没有头像的演员和制作人员
  FanartShow: False                         # 显示同人图（fanart 图）
  ExternalPlayerUrl: False                  # 是否开启外置播放器（仅 Emby）
  Danmaku: True                             # Web 弹幕（Emby：https://github.com/9channel/dd-danmaku；Jellyfin：https://github.com/Izumiko/jellyfin-danmaku）
  VideoTogether: True                       # 共同观影，详情见 https://videotogether.github.io/

ClientFilter:                               # 客户端过滤器
  Enable: False                             # 是否启用客户端过滤器
  Mode: BlackList # WhileList / BlackList   # 黑白名单模式
  ClientList:                               # 名单列表
    - Fileball
    - Infuse

HTTPStrm:                                   # HTTPStrm 相关配置（Strm 文件内容是 标准 HTTP URL）
  Enable: True                              # 是否开启 HttpStrm 重定向
  TransCode: False                          # False：强制关闭转码 True：保持原有转码设置
  FinalURL: True                            # 对 URL 进行重定向判断，找到非重定向地址再重定向给客户端，减少客户端重定向次数（适用于 Strm 内容是局域网地址但是想要在公网之中播放）
  PrefixList:                               # EmbyServer 中 Strm 文件的前缀（符合该前缀的 Strm 文件且被正确识别为 HTTP 协议都会路由到该规则下）
    - /Media/ANiOpen-Strm

AlistStrm:                                  # AlistStrm 相关配置（Strm 文件内容是 Alist 上文件的路径，目前仅支持适配 Alist V3）
  Enable: True                              # 是否启用 AlistStrm 重定向
  TransCode: False                          # False：强制关闭转码 True：保持原有转码设置
  RawURL: True                              # Fasle：响应 Alist 服务器的直链（要求客户端可以访问到 Alist） True：直接响应 Alist 上游的真实链接（alist api 中的 raw_url 属性）
  List:                                     # Alist 服务关配置列表
    - ADDR: http://host.docker.internal:5244 # Alist 服务器地址
      Token: alist-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # Token 优先级高于 Username 和 Password
      PrefixList:                           # EmbyServer 中 Strm 文件的前缀（符合该前缀的 Strm 文件都会路由到该规则下）
        - /Media/AList-Strm                 # 同一个 Alist 可以有多个前缀规则
    - ADDR: http://host.docker.internal:5678 # 可以填写多个配置
      Username: dav                         # Alist 服务器账号
      Password: xxxxxxxxxxxxx               # Alist 服务器密码
      PrefixList: 
        - /Media/XiaoYa-Strm

Subtitle:                                   # 字体相关设置（仅 Emby 支持）
  Enable: False                             # 启用
  SRT2ASS: True                             # SRT 字幕转 ASS 字幕
  ASSStyle:                                 # SRT 字幕转 ASS 字幕使用的样式
    - "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
    - "Style: Default,楷体,20,&H03FFFFFF,&H00FFFFFF,&H00000000,&H02000000,-1,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1"
```
