### ISSUE TITLE
[错误报告]: 开启Crx功能后点击首页轮播图无法正常进入对应媒体页面

### ISSUE THREAD

**Issue by Star-ZER0** [Akimio521/MediaWarp#41]
### 确认

- [x] 我的版本是最新版本，我的版本号与 [version](https://github.com/Akimio521/MediaWarp/releases/latest) 相同。
- [x] 我已经 [issue](https://github.com/Akimio521/MediaWarp/issues) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

0.1.1

### 当前程序版本的详细信息

{"AppVersion":"0.1.1","CommitHash":"e8e0a76712f573522166eadcfccf682a81a3ecd4","BuildData":"2025-06-02 10:36:57 +08:00","GoVersion":"go1.24.1","OS":"linux","Arch":"amd64"}

### 运行环境

Docker

### 媒体服务器类型

Jellyfin

### 媒体服务器版本

nyanmisaka/jellyfin:latest    a3deaaefacaf

### 客户端版本

浏览器 Microsoft Edge & Mozilla Firefox

### 问题类型

Web 美化/额外功能问题

### 问题描述

点击首页轮播图的MORE按钮后跳转至https://HOST:PORT/web/#/details?id=undefined&serverId=undefined并无限加载

### 发生问题时相关日志

```bash
███╗   ███╗███████╗██████╗ ██╗ █████╗ ██╗    ██╗ █████╗ ██████╗ ██████╗ 

████╗ ████║██╔════╝██╔══██╗██║██╔══██╗██║    ██║██╔══██╗██╔══██╗██╔══██╗

██╔████╔██║█████╗  ██║  ██║██║███████║██║ █╗ ██║███████║██████╔╝██████╔╝

██║╚██╔╝██║██╔══╝  ██║  ██║██║██╔══██║██║███╗██║██╔══██║██╔══██╗██╔═══╝ 

██║ ╚═╝ ██║███████╗██████╔╝██║██║  ██║╚███╔███╔╝██║  ██║██║  ██║██║     

╚═╝     ╚═╝╚══════╝╚═════╝ ╚═╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ 

=========================== MediaWarp 0.1.1 ===========================

【INFO】        2025-06-07 19:21:55 | 上游媒体服务器类型：Jellyfin，服务器地址：http://jellyfin:8096

【INFO】        2025-06-07 19:21:55 | MediaWarp 监听端口：9000

【INFO】        2025-06-07 19:21:55 | 客户端过滤中间件未启用

【INFO】        2025-06-07 19:21:55 | MediaWarp 启动成功

【Access】 2025-06-07 19:22:15 | 302 | 3.558587ms | GET     | 27.26.70.91 "/"

【Access】 2025-06-07 19:22:15 | 200 | 9.923767ms | GET     | 27.26.70.91 "/web/"

【Access】 2025-06-07 19:22:15 | 200 | 612.025µs  | GET     | 27.26.70.91 "/MediaWarp/static/jellyfin-crx/static/js/common-utils.js"

【Access】 2025-06-07 19:22:15 | 200 | 92.963µs   | GET     | 27.26.70.91 "/MediaWarp/static/jellyfin-crx/static/js/md5.min.js"

【Access】 2025-06-07 19:22:15 | 200 | 332.701µs  | GET     | 27.26.70.91 "/MediaWarp/static/jellyfin-crx/static/css/style.css"

【Access】 2025-06-07 19:22:15 | 200 | 250.472µs  | GET     | 27.26.70.91 "/MediaWarp/static/jellyfin-danmaku/ede.js"

【Access】 2025-06-07 19:22:15 | 200 | 1.116412ms | GET     | 27.26.70.91 "/MediaWarp/static/jellyfin-crx/static/js/jquery-3.6.0.min.js"

【Access】 2025-06-07 19:22:15 | 200 | 1.045871ms | GET     | 27.26.70.91 "/MediaWarp/static/jellyfin-crx/content/main.js"

【Access】 2025-06-07 19:22:16 | 200 | 4.754139ms | GET     | 27.26.70.91 "/web/config.json"

【Access】 2025-06-07 19:22:16 | 200 | 6.622329ms | GET     | 27.26.70.91 "/web/config.json"

【Access】 2025-06-07 19:22:16 | 200 | 8.943295ms | GET     | 27.26.70.91 "/web/config.json"

【Access】 2025-06-07 19:22:16 | 200 | 9.218288ms | GET     | 27.26.70.91 "/web/serviceworker.js"

【Access】 2025-06-07 19:22:16 | 200 | 1.794707ms | GET     | 27.26.70.91 "/System/Info/Public"

【Access】 2025-06-07 19:22:17 | 200 | 4.117974ms | GET     | 27.26.70.91 "/system/info/public"

【Access】 2025-06-07 19:22:17 | 200 | 4.629002ms | GET     | 27.26.70.91 "/web/config.json"

【Access】 2025-06-07 19:22:17 | 200 | 10.410711ms | GET     | 27.26.70.91 "/Branding/Css"

【Access】 2025-06-07 19:22:17 | 200 | 19.663422ms | GET     | 27.26.70.91 "/System/Info"

【Access】 2025-06-07 19:22:17 | 200 | 2.820639ms | GET     | 27.26.70.91 "/Users/a2ff8dc942f24b388a4d143dae1dd071"

【Access】 2025-06-07 19:22:17 | 200 | 8.929214ms | GET     | 27.26.70.91 "/DisplayPreferences/usersettings?userId=a2ff8dc942f24b388a4d143dae1dd071&client=emby"

【Access】 2025-06-07 19:22:17 | 204 | 28.943587ms | POST    | 27.26.70.91 "/Sessions/Capabilities/Full"

【Access】 2025-06-07 19:22:17 | 304 | 645.408µs  | GET     | 27.26.70.91 "/web/serviceworker.js"

【Access】 2025-06-07 19:22:17 | 200 | 8.784066ms | GET     | 27.26.70.91 "/UserViews?userId=a2ff8dc942f24b388a4d143dae1dd071"

【Access】 2025-06-07 19:22:17 | 200 | 38.914641ms | GET     | 27.26.70.91 "/Users/a2ff8dc942f24b388a4d143dae1dd071/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Book"

【Access】 2025-06-07 19:22:17 | 200 | 39.05459ms | GET     | 27.26.70.91 "/Users/a2ff8dc942f24b388a4d143dae1dd071/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=b57645a60da3b013c7ca693c971d8d2f"

【Access】 2025-06-07 19:22:17 | 200 | 49.265307ms | GET     | 27.26.70.91 "/Users/a2ff8dc942f24b388a4d143dae1dd071/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio"

【Access】 2025-06-07 19:22:17 | 200 | 46.89224ms | GET     | 27.26.70.91 "/Users/a2ff8dc942f24b388a4d143dae1dd071/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=3dbd3fe299e95ad098d0ff12b2c23a65"

【Access】 2025-06-07 19:22:17 | 200 | 59.040962ms | GET     | 27.26.70.91 "/Users/a2ff8dc942f24b388a4d143dae1dd071/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video"

【Access】 2025-06-07 19:22:17 | 200 | 83.703687ms | GET     | 27.26.70.91 "/Users/a2ff8dc942f24b388a4d143dae1dd071/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=cf89f8857e796234723a88f1f42a706c"

【Access】 2025-06-07 19:22:17 | 200 | 95.772766ms | GET     | 27.26.70.91 "/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CPath%2CMediaSourceCount&UserId=a2ff8dc942f24b388a4d143dae1dd071&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2024-06-07T11%3A22%3A17.875Z&EnableResumable=false&EnableRewatching=false"

【Access】 2025-06-07 19:22:18 | 200 | 25.260878ms | GET     | 27.26.70.91 "/Users/a2ff8dc942f24b388a4d143dae1dd071/Items?ImageTypes=Backdrop&EnableImageTypes=Backdrop&IncludeItemTypes=Movie%2CSeries&SortBy=ProductionYear%2C%20PremiereDate%2C%20SortName&Recursive=true&ImageTypeLimit=1&Limit=10&Fields=Overview&SortOrder=Descending&EnableUserData=false&EnableTotalRecordCount=false"

【Access】 2025-06-07 19:22:19 | 304 | 11.950542ms | GET     | 27.26.70.91 "/Items/a94a8c848b2593d26073eb4f041fa484/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 8.980097ms | GET     | 27.26.70.91 "/Items/36f9b6beba5c72fadb8e42571d098fa4/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 13.675858ms | GET     | 27.26.70.91 "/Items/b6daa8d1a96feb804a9aa1cfca3dde6f/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 6.993818ms | GET     | 27.26.70.91 "/Items/950d1bc4158e5ce5cba734df208b15dd/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 5.315758ms | GET     | 27.26.70.91 "/Items/0c780e6176fe1e47a765f493e6764ed4/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 17.344241ms | GET     | 27.26.70.91 "/Items/161677ef2f7d888f5401596d353b0513/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 9.857663ms | GET     | 27.26.70.91 "/Items/7535e229aa92a1578f419dab2efb11bc/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 12.889189ms | GET     | 27.26.70.91 "/Items/2076fb1ee0d03a50804e279ed8071cd1/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 12.33288ms | GET     | 27.26.70.91 "/Items/3fa37ab03c6efbf53b0cb0ef9da5cb62/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:19 | 304 | 1.324731ms | GET     | 27.26.70.91 "/Items/a9afb5c51473d4d0358ba2af789ec123/Images/Backdrop?maxWidth=3000&adjustForPixelRatio=false&quality=80"

【Access】 2025-06-07 19:22:21 | 200 | 19.877146ms | GET     | 27.26.70.91 "/Items/a94a8c848b2593d26073eb4f041fa484?userId=a2ff8dc942f24b388a4d143dae1dd071"

【Access】 2025-06-07 19:22:23 | 200 | 2.517477ms | GET     | 27.26.70.91 "/System/Endpoint"

【Access】 2025-06-07 19:22:23 | 200 | 15.492532ms | GET     | 27.26.70.91 "/Playback/BitrateTest?Size=500000"

【Access】 2025-06-07 19:22:23 | 200 | 17.028395ms | GET     | 27.26.70.91 "/Playback/BitrateTest?Size=1000000"
```

### 发生问题时配置文件

```yaml
Port: 9000                                  # MideWarp 监听端口

MediaServer:                                # 媒体服务器相关设置
  Type: Jellyfin                            # 媒体服务器类型（可选选项：Emby、Jellyfin）
  ADDR: http://jellyfin:8096                # 媒体服务器地址
  AUTH: faxxxxxxxxxxxxxxxxxxxxxxxxxxxx0f    # 媒体服务器认证方式

Logger:                                     # 日志设定
  AccessLogger:                             # 访问日志设定
    Console: True                           # 是否将访问日志文件输出到终端中
    File: False                             # 是否将访问日志文件记录到文件中
  ServiceLogger:                            # 服务日志设定
    Console: True                           # 是否将服务日志文件输出到终端中
    File: True                              # 是否将服务日志文件记录到文件中

Web:                                        # Web 页面修改相关设置
  Enable: True                              # 总开关
  Custom: False                             # 是否加载自定义静态资源
  Index: False                              # 是否从 custom 目录读取 index.html 文件 
  Head: |                                   # 是否添加自定义字段到 index.html 的头部中

  Crx: True                                 # crx 美化（Emby：https://github.com/Nolovenodie/emby-crx；Jellyfin：https://github.com/newday-life/jellyfin-crx）
  ActorPlus: False                          # 过滤没有头像的演员和制作人员
  FanartShow: False                         # 显示同人图（fanart 图）
  ExternalPlayerUrl: False                  # 是否开启外置播放器（仅 Emby）
  Danmaku: True                             # Web 弹幕（Emby：https://github.com/9channel/dd-danmaku；Jellyfin：https://github.com/Izumiko/jellyfin-danmaku）
  VideoTogether: True                       # 共同观影，详情见 https://videotogether.github.io/

ClientFilter:                               # 客户端过滤器
  Enable: False                             # 是否启用客户端过滤器
  Mode: BlackList # WhileList / BlackList   # 黑白名单模式
  ClientList:                               # 名单列表
    - Fileball
    - Infuse

HTTPStrm:                                   # HTTPStrm 相关配置（Strm 文件内容是 标准 HTTP URL）
  Enable: True                              # 是否开启 HttpStrm 重定向
  TransCode: False                          # False：强制关闭转码 True：保持原有转码设置
  FinalURL: True                            # 对 URL 进行重定向判断，找到非重定向地址再重定向给客户端，减少客户端重定向次数（适用于 Strm 内容是局域网地址但是想要在公网之中播放）
  PrefixList:                               # EmbyServer 中 Strm 文件的前缀（符合该前缀的 Strm 文件且被正确识别为 HTTP 协议都会路由到该规则下）
    - /Media/ANiOpen-Strm

AlistStrm:                                  # AlistStrm 相关配置（Strm 文件内容是 Alist 上文件的路径，目前仅支持适配 Alist V3）
  Enable: True                              # 是否启用 AlistStrm 重定向
  TransCode: False                          # False：强制关闭转码 True：保持原有转码设置
  RawURL: True                              # Fasle：响应 Alist 服务器的直链（要求客户端可以访问到 Alist） True：直接响应 Alist 上游的真实链接（alist api 中的 raw_url 属性）
  List:                                     # Alist 服务关配置列表
    - ADDR: http://host.docker.internal:5244 # Alist 服务器地址
      Token: alist-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # Token 优先级高于 Username 和 Password
      PrefixList:                           # EmbyServer 中 Strm 文件的前缀（符合该前缀的 Strm 文件都会路由到该规则下）
        - /Media/AList-Strm                 # 同一个 Alist 可以有多个前缀规则
    - ADDR: http://host.docker.internal:5678 # 可以填写多个配置
      Username: dav                         # Alist 服务器账号
      Password: xxxxxxxxxxxxx               # Alist 服务器密码
      PrefixList: 
        - /Media/XiaoYa-Strm

Subtitle:                                   # 字体相关设置（仅 Emby 支持）
  Enable: False                             # 启用
  SRT2ASS: True                             # SRT 字幕转 ASS 字幕
  ASSStyle:                                 # SRT 字幕转 ASS 字幕使用的样式
    - "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
    - "Style: Default,楷体,20,&H03FFFFFF,&H00FFFFFF,&H00000000,&H02000000,-1,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1"
```
